ftwitter/src/accounts/api/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from tweets.api.views import (
    TweetListAPIView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/tweet/$', TweetListAPIView.as_view(), name='list'), # /api/tweet/
]

ftwitter/src/accounts/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from .views import (
    UserDetailView,
    UserFollowView
    )
from django.conf import settings



urlpatterns = [
   

    url(r'^(?P<username>[\w.@+-]+)/$',UserDetailView.as_view(),name='detail'), #api/tweets/
    url(r'^(?P<username>[\w.@+-]+)/follow/$',UserFollowView.as_view(),name='follow'),

]

ftwitter/src/tweets/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from .views import (
    RetweetView,
	TweetDetailView,
	TweetListView,
	TweetCreateView,TweetUpdateView,
	TweetDeleteView)
from django.conf import settings

from django.views.generic.base import RedirectView

urlpatterns = [
   
    url(r'^$',RedirectView.as_view(url='/')),
    url(r'^search/$',TweetListView.as_view(),name='list'), #/tweets/
    url(r'^create/$',TweetCreateView.as_view(),name='create'),
    url(r'^(?P<pk>\d+)/$',TweetDetailView.as_view(),name='detail'), #/tweet/1/detail
    url(r'^(?P<pk>\d+)/retweet/$',RetweetView.as_view(),name='retweet'),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),  #/tweet/1/update
    url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'), #/tweet/1/delete
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ftwitter/src/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy
from django.db.models.signals import post_save
# Create your models here.
class UserProfileManager(models.Manager):
	use_for_related_fields=True
	def all(self):
		qs=self.get_queryset().all()
		#print(self.instance)
		try:
			if self.instance:
				qs=qs.exclude(user=self.instance)
		except:
			pass
		return qs
	def toggle_follow(self,user,to_toggle_user):
		user_profile,created=UserProfile.objects.get_or_create(user=user)
		if to_toggle_user in user_profile.following.all():
			user_profile.following.remove(to_toggle_user)
			added=False
		else:
			user_profile.following.add(to_toggle_user)
			added=True
		return added
	
	def is_following(self,user,followed_by_user):
		user_profile,created=UserProfile.objects.get_or_create(user=user)
		if created:
			return False
		if followed_by_user in user_profile.following.all():
			return True
		return False


class UserProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='profile')
	following = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='followed_by')


	objects=UserProfileManager()

	def __str__(self):
		return str(self.following.all().count())

	def get_following(self):
		users=self.following.all()
		return users.exclude(username=self.user.username)	

	def get_follow_url(self):
		return reverse_lazy("profiles:follow",kwargs={"username":self.user.username})

	def get_absolute_url(self):
		return reverse_lazy("profiles:detail",kwargs={"username":self.user.username})


def post_save_user_receiver(sender,instance,created,*args,**kwargs):
	print(instance)
	if created:
		new_profile = UserProfile.objects.get_or_create(user=instance)

post_save.connect(post_save_user_receiver,sender=settings.AUTH_USER_MODEL)

ftwitter/src/tweets/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.
class TweetManager(models.Manager):
	def retweet(self,user,parent_obj):
		if parent_obj.parent:
			og_parent=parent_obj.parent
		else:
			og_parent=parent_obj

		qs=self.get_queryset().filter(user=user,parent=og_parent)
		if qs.exists():
			return None
		obj=self.model(
			parent=og_parent,
			user=user,
			content=parent_obj.content,
			image=parent_obj.image,

			)
		obj.save()

		return obj

	def like_toggle(self,user,tweet_obj):
		if user in tweet_obj.liked.all():
			is_liked=False
			tweet_obj.liked.remove(user)
		else:
		    is_liked=True
		    tweet_obj.liked.add(user)
		return is_liked		


		

class Tweet(models.Model):



	user =models.ForeignKey(settings.AUTH_USER_MODEL)
	parent = models.ForeignKey("self",blank=True,null=True)
	content = models.CharField(max_length=140)
	timestamp=models.DateTimeField(auto_now_add=True)
	liked=models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='liked') 
	updated=models.DateTimeField(auto_now=True)
	image = models.FileField(upload_to='images',blank=True)

	objects=TweetManager()


	def __str__(self):
		return str(self.content)
		
	def get_absolute_url(self):
		return reverse("tweet:detail", kwargs={"pk":self.pk})

	class Meta:
		ordering = ['-timestamp']
		
			

ftwitter/src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    email = forms.EmailField()
    pass1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    pass2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    def clean_password2(self):
        pass1 = self.cleaned_data.get('pass1')
        pass2 = self.cleaned_data.get('pass2')
        if pass1 != pass2:
            raise forms.ValidationError("Password must match")
        return pass1

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__icontains=username).exists():
            raise forms.ValidationError("This username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__icontains=email).exists():
            raise forms.ValidationError(" Email is already registered.") 
        if not email.endswith('@nu.edu.pk'):
            raise forms.ValidationError("Only nu.edu.pk email addresses allowed")
        return email

ftwitter/src/accounts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import DetailView
from django.views import View
from django.views.generic.edit import FormView
# Create your views here.

from .forms import UserRegisterForm
from .models import UserProfile
from django.contrib.auth import get_user_model
# Create your views here.


from .models import UserProfile

User =get_user_model()


class UserRegisterView(FormView):
    template_name = 'accounts/user_register_form.html'
    form_class = UserRegisterForm
    success_url = '/login'

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("pass1")
        print(password)
        new_user = User.objects.create(username=username, email=email)
        new_user.set_password(password)
        new_user.save()
        return super(UserRegisterView, self).form_valid(form)


class UserDetailView(DetailView):
	template_name = 'accounts/user_detail.html'
	queryset = User.objects.all()

	def get_object(self):
		return get_object_or_404(User, username__iexact=self.kwargs.get("username"))

	def get_context_data(self,*args,**kwargs):
		context=super(UserDetailView,self).get_context_data(*args,**kwargs)
		context['following']=UserProfile.objects.is_following(self.request.user,self.get_object())
		return context

class UserFollowView(View):
	def get(self,request,username,*args,**kwargs):
		toggle_user=get_object_or_404(User,username__iexact=username)
		if request.user.is_authenticated():
			is_following=UserProfile.objects.toggle_follow(request.user,toggle_user)
		return redirect("profiles:detail",username=username)
		

ftwitter/src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% block content%}


  
	<div class="row">
    <div class="col-sm-3 col-xs-12">
    <h1>{{object.username}}</h1>
    <p>Followers:{{object.followed_by.all.count}}</p>
    {%if request.user %}
    <p><a class="btn btn-link" href='{{ object.profile.get_follow_url}}'>{% if following %}UnFollow{% else %}Follow{%endif%}</a></p><br/>
    {% endif %}
    <h1>Following <small>{{object.profile.get_following.count}}</small></h1>
    {% for user in object.profile.get_following%}
     <a href="/{{user.username}}">{{user.username}}</a><br/>
     {%empty%}
      <p>Not following</p>
    {% endfor%}

    <h1>Followed By</h1>
    {% for profile in object.followed_by.all %}
     <a href="/{{profile.user.username}}">{{profile.user.username}}</a><br/>
     {%empty%}
     <p>Not followed</p>
    {% endfor%}
  </div>
     <div class="card text-white bg-dark "   style="width:550px; padding: 24px; margin-left: 25%; margin-top: 7px;">
	 {% for tweet in object.tweet_set.all %}
  
   
    	{% if tweet.image.url != null %}
        <img class="card-img-top" src="{{ tweet.image.url}}" alt=" " style="width: 500px;">
        {% endif %}
      	<div class="card-body">
        <h5 class="card-title">{{tweet.user}}</h5>
        <p class="card-text">{{tweet.content }}.</p>
        <hr class=\'line\'/><a href ='/tweet/{{tweet.id}}'>View</a>
        <a href ='/tweet/{{tweet.id}}/retweet/'>Retweet</a></hr>
      
        </div>
    {% endfor %}

    
  
</div>
{% endblock content %}    

ftwitter/src/accounts/templates/accounts/user_register_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}Register | {{ block.super }}{% endblock title %}


{% block content %}
<div style="margin-left: 30%; margin-top: 5%; border: 1px solid  lightgrey;
  border-radius: 8px; padding: 10px; max-width: 40%; 
  -moz-box-shadow:    1px 1px 1px 1px #ccc;
  -webkit-box-shadow: 1px 1px 1px 1px #ccc;
  box-shadow:         5px 3px 1px 2px #ccc;">
       <div class='col-sm-6 col-sm-offset-3'>
        <h1>Register</h1>
                <form class='form {% if form_class %}{{ form_class }}{% endif %}' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
           	{% csrf_token %}
            {{ form|crispy }}
            <input class='btn btn-primary' type="submit" value="Register" style="margin-left: 170%;  margin-top: 2%" />
        </form>
    </div>
</div>
{% endblock content %}